
version: "3.9"
    
services:
  wp_mw_scanner_db:
    image: mysql:8.0
    container_name: wp_mw_scanner-db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wp_mw_scanner
      MYSQL_USER: wp_mw_scanner
      MYSQL_PASSWORD: wp_mw_scanner

  wp_mw_scanner_wp:
    depends_on:
       - wp_mw_scanner_db
    image: sanda3cs/wordpress7.4:latest
    container_name: wp_mw_scanner-wp
    ports:
      - 80:80
    environment:
      uploads_limit: 128
      memory_limit: 512
      
volumes:
  db_data: {}
  wordpress_data: {}

networks:
  localnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 162.11.1.0/24
          gateway: 162.11.1.1