on: 
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install gcloud SDK.
        run: |
          sudo apt-get update && sudo apt-get install google-cloud-sdk  && sudo apt-get install zip
      - name: Activate Service Account 
        env: 
          GCLOUD_AUTH: ${{ secrets.WPMALSCAN_SA_KEY }}
        run: |
          echo "$GCLOUD_AUTH" | base64 --decode > "$HOME"/gcloud.json
          sh -c "gcloud auth activate-service-account --key-file=$HOME/gcloud.json $*"
          
      - shell: bash
        run: |
          gsutil cp update-info.json gs://wp-malware-scanner.3cs.technology/info.json
          zip -r update.zip wp-malware-scanner
          gsutil cp update.zip gs://wp-malware-scanner.3cs.technology/plugin.zip
